spring:
  application:
    name: eureka-server-ha
security:
  basic:
    enabled: true
  user:
    name: admin
    password: fangming
---
spring:
  profiles: peer1
server:
  port: 8761
eureka:
  instance:
    hostname: peer1 #指定当profile=peer1时，主机名是peer1
  client:
    register-with-eureka: false
#    registerWithEureka: false
    fetch-registry: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://admin:fangming@peer2:8762/eureka,http://admin:fangming@peer3:8763/eureka

---
spring:
  profiles: peer2
server:
  port: 8762
eureka:
  instance:
    hostname: peer2 #指定当profile=peer2时，主机名是peer2
  client:
    register-with-eureka: false
#    registerWithEureka: false
    fetch-registry: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://admin:fangming@peer1:8761/eureka,http://admin:fangming@peer3:8763/eureka
---
spring:
  profiles: peer3
server:
  port: 8763
eureka:
  instance:
    hostname: peer3 #指定当profile=peer2时，主机名是peer2
  client:
    register-with-eureka: false
#    registerWithEureka: false
    fetch-registry: false
#    fetchRegistry: false
    service-url:
      defaultZone: http://admin:fangming@peer1:8761/eureka,http://admin:fangming@peer2:8762/eureka
