server:
  port: 9092
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:fangming@localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
user:
  userServiceUrl: http://localhost:9091/user/{id}
spring:
  application:
    name: spring-boot-quickstart-consumer
#  jpa:
#    generate-ddl: false
#    show-sql: true
#    hibernate:
#      ddl-auto: none
#  datasource:
#    platform: h2
#    schema: classpath:schema.sql
#    data: classpath:data.sql
#logging:
#  level:
#    root: INFO
#    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.hibernate.type.descriptor.sql.BasicExtrator: TRACE
