server:
  port: 9091
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:fangming@localhost:8761/eureka  #注册 中心已经开启认证
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: spring-boot-quickstart
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtrator: TRACE
actuator:
  info:
    app:
      name: @project.artifactId@
      encoding: @project.build.sourceEncoding@
      java:
        source: @java.version@
        target: @java.version@

#info:
#  app:
#    name: @projecdt.artifactId@
#    encoding: @project.build.sourceEncoding@
#    java:
#      source: @java.version@
#      target: @java.version@
